import {
  Airplane,
  Alarm,
  Archive,
  BookOpenText,
  Briefcase,
  Bug,
  CalendarBlank,
  Camera,
  ChartBar,
  ChatCircle,
  CheckCircle,
  Cloud,
  Code,
  Compass,
  Crown,
  Database,
  Envelope,
  Flag,
  FolderSimple,
  GearSix,
  Globe,
  GraduationCap,
  Heart,
  House,
  Image,
  Key,
  Lightbulb,
  LinkSimple,
  ListBullets,
  Lock,
  MapPin,
  Megaphone,
  MusicNote,
  NotePencil,
  Palette,
  Paperclip,
  Phone,
  Plant,
  Rocket,
  Shield,
  ShoppingCart,
  Sparkle,
  Star,
  Sun,
  Tag,
  Target,
  TerminalWindow,
  Timer,
  Trash,
  Trophy,
  User,
  Users,
  Wrench,
  type Icon as PhosphorIcon,
} from "@phosphor-icons/react";

export const AFFINE_ICONS: readonly {
  name: string;
  label: string;
  keywords: string;
  Icon: PhosphorIcon;
}[] = [
  {
    name: "lightbulb",
    label: "Lightbulb",
    keywords: "idea light bulb",
    Icon: Lightbulb,
  },
  {
    name: "note-pencil",
    label: "Note",
    keywords: "note write edit",
    Icon: NotePencil,
  },
  {
    name: "book",
    label: "Book",
    keywords: "book read knowledge",
    Icon: BookOpenText,
  },
  {
    name: "folder",
    label: "Folder",
    keywords: "folder file collection",
    Icon: FolderSimple,
  },
  {
    name: "archive",
    label: "Archive",
    keywords: "archive box storage",
    Icon: Archive,
  },
  {
    name: "calendar",
    label: "Calendar",
    keywords: "calendar date journal",
    Icon: CalendarBlank,
  },
  { name: "timer", label: "Timer", keywords: "timer clock time", Icon: Timer },
  {
    name: "alarm",
    label: "Alarm",
    keywords: "alarm clock reminder",
    Icon: Alarm,
  },
  {
    name: "target",
    label: "Target",
    keywords: "target goal objective",
    Icon: Target,
  },
  {
    name: "check",
    label: "Check circle",
    keywords: "check done task complete",
    Icon: CheckCircle,
  },
  {
    name: "list",
    label: "List",
    keywords: "list notes tasks",
    Icon: ListBullets,
  },
  { name: "tag", label: "Tag", keywords: "tag label topic", Icon: Tag },
  {
    name: "star",
    label: "Star",
    keywords: "star favorite important",
    Icon: Star,
  },
  {
    name: "sparkle",
    label: "Sparkle",
    keywords: "sparkle magic ai",
    Icon: Sparkle,
  },
  {
    name: "heart",
    label: "Heart",
    keywords: "heart love favorite",
    Icon: Heart,
  },
  {
    name: "crown",
    label: "Crown",
    keywords: "crown premium leader",
    Icon: Crown,
  },
  {
    name: "trophy",
    label: "Trophy",
    keywords: "trophy win award",
    Icon: Trophy,
  },
  {
    name: "rocket",
    label: "Rocket",
    keywords: "rocket launch project",
    Icon: Rocket,
  },
  { name: "plant", label: "Plant", keywords: "plant grow nature", Icon: Plant },
  { name: "sun", label: "Sun", keywords: "sun light weather", Icon: Sun },
  {
    name: "globe",
    label: "Globe",
    keywords: "globe earth world web",
    Icon: Globe,
  },
  {
    name: "compass",
    label: "Compass",
    keywords: "compass direction navigate",
    Icon: Compass,
  },
  {
    name: "map-pin",
    label: "Map pin",
    keywords: "map pin location place",
    Icon: MapPin,
  },
  {
    name: "airplane",
    label: "Airplane",
    keywords: "airplane travel flight",
    Icon: Airplane,
  },
  { name: "house", label: "House", keywords: "house home", Icon: House },
  {
    name: "briefcase",
    label: "Briefcase",
    keywords: "briefcase work business",
    Icon: Briefcase,
  },
  {
    name: "graduation",
    label: "Graduation",
    keywords: "graduation school education",
    Icon: GraduationCap,
  },
  {
    name: "users",
    label: "People",
    keywords: "people users team group",
    Icon: Users,
  },
  {
    name: "user",
    label: "Person",
    keywords: "person user profile",
    Icon: User,
  },
  {
    name: "chat",
    label: "Chat",
    keywords: "chat message conversation",
    Icon: ChatCircle,
  },
  {
    name: "envelope",
    label: "Envelope",
    keywords: "envelope email mail",
    Icon: Envelope,
  },
  {
    name: "megaphone",
    label: "Megaphone",
    keywords: "megaphone announce marketing",
    Icon: Megaphone,
  },
  { name: "phone", label: "Phone", keywords: "phone call mobile", Icon: Phone },
  {
    name: "camera",
    label: "Camera",
    keywords: "camera photo image",
    Icon: Camera,
  },
  {
    name: "image",
    label: "Image",
    keywords: "image photo picture",
    Icon: Image,
  },
  {
    name: "music",
    label: "Music",
    keywords: "music audio note",
    Icon: MusicNote,
  },
  {
    name: "palette",
    label: "Palette",
    keywords: "palette art design color",
    Icon: Palette,
  },
  {
    name: "code",
    label: "Code",
    keywords: "code development programming",
    Icon: Code,
  },
  {
    name: "terminal",
    label: "Terminal",
    keywords: "terminal command code",
    Icon: TerminalWindow,
  },
  {
    name: "database",
    label: "Database",
    keywords: "database data storage",
    Icon: Database,
  },
  {
    name: "chart",
    label: "Chart",
    keywords: "chart analytics graph",
    Icon: ChartBar,
  },
  { name: "bug", label: "Bug", keywords: "bug issue debug", Icon: Bug },
  {
    name: "gear",
    label: "Gear",
    keywords: "gear settings configuration",
    Icon: GearSix,
  },
  {
    name: "wrench",
    label: "Wrench",
    keywords: "wrench tool repair",
    Icon: Wrench,
  },
  { name: "key", label: "Key", keywords: "key access password", Icon: Key },
  { name: "lock", label: "Lock", keywords: "lock secure private", Icon: Lock },
  {
    name: "shield",
    label: "Shield",
    keywords: "shield security protect",
    Icon: Shield,
  },
  {
    name: "cloud",
    label: "Cloud",
    keywords: "cloud weather storage",
    Icon: Cloud,
  },
  {
    name: "link",
    label: "Link",
    keywords: "link connection url",
    Icon: LinkSimple,
  },
  {
    name: "paperclip",
    label: "Paperclip",
    keywords: "paperclip attachment",
    Icon: Paperclip,
  },
  {
    name: "flag",
    label: "Flag",
    keywords: "flag milestone marker",
    Icon: Flag,
  },
  {
    name: "cart",
    label: "Cart",
    keywords: "cart shopping store",
    Icon: ShoppingCart,
  },
  {
    name: "trash",
    label: "Trash",
    keywords: "trash delete remove",
    Icon: Trash,
  },
];

export function iconDefinition(name: string) {
  return AFFINE_ICONS.find((icon) => icon.name === name);
}
